<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Homecenter.Microservice.Api.LabelPrinting.Abstractions\Homecenter.Microservice.Api.LabelPrinting.Abstractions.csproj" />
    <ProjectReference Include="..\Homecenter.Microservice.Api.LabelPrinting.Entities\Homecenter.Microservice.Api.LabelPrinting.Entities.csproj" />
    <ProjectReference Include="..\Homecenter.Microservice.Api.LabelPrinting.Data.Transfer.Object\Homecenter.Microservice.Api.LabelPrinting.Data.Transfer.Object.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.10" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
